# Site wide configuration

title: "Vidtech Services"
description: "Serving the electrical industry"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: "http://localhost"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: ""
  web: ""
  twitter: ""
  bio: ""
  avatar: "" # 160x160 px image for author byline
  google:
    plus: "+"
    ad-client: ""
    ad-slot:
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - ciScripts
